(define (problem schedule-60)
(:domain schedule)
(:objects
    N2
    M2
    L2
    K2
    J2
    I2
    H2
    G2
    F2
    E2
    D2
    C2
    B2
    A2
    Z1
    W1
    V1
    U1
    S1
    R1
    P1
    Q1
    O1
    N1
    M1
    L1
    K1
    J1
    I1
    H1
    G1
    F1
    E1
    D1
    C1
    B1
    A1
    Z0
    W0
    V0
    U0
    S0
    R0
    P0
    Q0
    O0
    N0
    M0
    L0
    K0
    J0
    I0
    H0
    G0
    F0
    E0
    D0
    C0
    CIRCULAR
    TWO
    THREE
    BLUE
    YELLOW
    BACK
    RED
    B0
    FRONT
    ONE
    BLACK
    OBLONG
    A0
)
(:init

(SHAPE A0 OBLONG)
(SURFACE-CONDITION A0 ROUGH)
(PAINTED A0 YELLOW)
(TEMPERATURE A0 COLD)
(HAS-HOLE A0 ONE BACK)

(SHAPE B0 CYLINDRICAL)
(SURFACE-CONDITION B0 POLISHED)
(PAINTED B0 RED)
(TEMPERATURE B0 COLD)
(HAS-HOLE B0 TWO FRONT)

(SHAPE C0 OBLONG)
(SURFACE-CONDITION C0 POLISHED)
(PAINTED C0 BLACK)
(TEMPERATURE C0 COLD)
(HAS-HOLE C0 ONE BACK)

(SHAPE D0 CYLINDRICAL)
(SURFACE-CONDITION D0 ROUGH)
(PAINTED D0 BLACK)
(TEMPERATURE D0 COLD)
(HAS-HOLE D0 TWO BACK)

(SHAPE E0 OBLONG)
(SURFACE-CONDITION E0 POLISHED)
(PAINTED E0 BLUE)
(TEMPERATURE E0 COLD)
(HAS-HOLE E0 TWO FRONT)

(SHAPE F0 OBLONG)
(SURFACE-CONDITION F0 ROUGH)
(PAINTED F0 BLUE)
(TEMPERATURE F0 COLD)
(HAS-HOLE F0 ONE FRONT)

(SHAPE G0 OBLONG)
(SURFACE-CONDITION G0 POLISHED)
(PAINTED G0 YELLOW)
(TEMPERATURE G0 COLD)
(HAS-HOLE G0 ONE FRONT)

(SHAPE H0 OBLONG)
(SURFACE-CONDITION H0 ROUGH)
(PAINTED H0 BLUE)
(TEMPERATURE H0 COLD)
(HAS-HOLE H0 ONE BACK)

(SHAPE I0 CIRCULAR)
(SURFACE-CONDITION I0 ROUGH)
(PAINTED I0 BLUE)
(TEMPERATURE I0 COLD)
(HAS-HOLE I0 TWO FRONT)

(SHAPE J0 CYLINDRICAL)
(SURFACE-CONDITION J0 POLISHED)
(PAINTED J0 YELLOW)
(TEMPERATURE J0 COLD)
(HAS-HOLE J0 THREE FRONT)

(SHAPE K0 OBLONG)
(SURFACE-CONDITION K0 ROUGH)
(PAINTED K0 BLACK)
(TEMPERATURE K0 COLD)
(HAS-HOLE K0 TWO BACK)

(SHAPE L0 OBLONG)
(SURFACE-CONDITION L0 POLISHED)
(PAINTED L0 BLUE)
(TEMPERATURE L0 COLD)
(HAS-HOLE L0 THREE BACK)

(SHAPE M0 CYLINDRICAL)
(SURFACE-CONDITION M0 ROUGH)
(PAINTED M0 BLUE)
(TEMPERATURE M0 COLD)
(HAS-HOLE M0 TWO FRONT)

(SHAPE N0 CIRCULAR)
(SURFACE-CONDITION N0 ROUGH)
(PAINTED N0 BLUE)
(TEMPERATURE N0 COLD)
(HAS-HOLE N0 THREE FRONT)

(SHAPE O0 OBLONG)
(SURFACE-CONDITION O0 POLISHED)
(PAINTED O0 YELLOW)
(TEMPERATURE O0 COLD)
(HAS-HOLE O0 ONE FRONT)

(SHAPE P0 OBLONG)
(SURFACE-CONDITION P0 SMOOTH)
(PAINTED P0 BLACK)
(TEMPERATURE P0 COLD)
(HAS-HOLE P0 THREE FRONT)

(SHAPE Q0 OBLONG)
(SURFACE-CONDITION Q0 ROUGH)
(PAINTED Q0 YELLOW)
(TEMPERATURE Q0 COLD)
(HAS-HOLE Q0 TWO FRONT)

(SHAPE R0 OBLONG)
(SURFACE-CONDITION R0 POLISHED)
(PAINTED R0 RED)
(TEMPERATURE R0 COLD)
(HAS-HOLE R0 THREE FRONT)

(SHAPE S0 OBLONG)
(SURFACE-CONDITION S0 ROUGH)
(PAINTED S0 BLUE)
(TEMPERATURE S0 COLD)
(HAS-HOLE S0 TWO FRONT)

(SHAPE U0 CIRCULAR)
(SURFACE-CONDITION U0 POLISHED)
(PAINTED U0 RED)
(TEMPERATURE U0 COLD)
(HAS-HOLE U0 ONE BACK)

(SHAPE V0 CYLINDRICAL)
(SURFACE-CONDITION V0 ROUGH)
(PAINTED V0 RED)
(TEMPERATURE V0 COLD)
(HAS-HOLE V0 TWO BACK)

(SHAPE W0 OBLONG)
(SURFACE-CONDITION W0 POLISHED)
(PAINTED W0 RED)
(TEMPERATURE W0 COLD)
(HAS-HOLE W0 ONE BACK)

(SHAPE Z0 OBLONG)
(SURFACE-CONDITION Z0 ROUGH)
(PAINTED Z0 YELLOW)
(TEMPERATURE Z0 COLD)
(HAS-HOLE Z0 TWO BACK)

(SHAPE A1 OBLONG)
(SURFACE-CONDITION A1 SMOOTH)
(PAINTED A1 BLACK)
(TEMPERATURE A1 COLD)
(HAS-HOLE A1 ONE BACK)

(SHAPE B1 OBLONG)
(SURFACE-CONDITION B1 ROUGH)
(PAINTED B1 BLUE)
(TEMPERATURE B1 COLD)
(HAS-HOLE B1 ONE BACK)

(SHAPE C1 OBLONG)
(SURFACE-CONDITION C1 ROUGH)
(PAINTED C1 RED)
(TEMPERATURE C1 COLD)
(HAS-HOLE C1 ONE FRONT)

(SHAPE D1 OBLONG)
(SURFACE-CONDITION D1 ROUGH)
(PAINTED D1 BLUE)
(TEMPERATURE D1 COLD)
(HAS-HOLE D1 TWO BACK)

(SHAPE E1 CIRCULAR)
(SURFACE-CONDITION E1 POLISHED)
(PAINTED E1 RED)
(TEMPERATURE E1 COLD)
(HAS-HOLE E1 THREE FRONT)

(SHAPE F1 OBLONG)
(SURFACE-CONDITION F1 POLISHED)
(PAINTED F1 BLACK)
(TEMPERATURE F1 COLD)
(HAS-HOLE F1 THREE FRONT)

(SHAPE G1 CIRCULAR)
(SURFACE-CONDITION G1 ROUGH)
(PAINTED G1 YELLOW)
(TEMPERATURE G1 COLD)
(HAS-HOLE G1 TWO BACK)

(SHAPE H1 OBLONG)
(SURFACE-CONDITION H1 SMOOTH)
(PAINTED H1 BLUE)
(TEMPERATURE H1 COLD)
(HAS-HOLE H1 TWO BACK)

(SHAPE I1 OBLONG)
(SURFACE-CONDITION I1 POLISHED)
(PAINTED I1 YELLOW)
(TEMPERATURE I1 COLD)
(HAS-HOLE I1 TWO FRONT)

(SHAPE J1 OBLONG)
(SURFACE-CONDITION J1 SMOOTH)
(PAINTED J1 YELLOW)
(TEMPERATURE J1 COLD)
(HAS-HOLE J1 ONE BACK)

(SHAPE K1 OBLONG)
(SURFACE-CONDITION K1 ROUGH)
(PAINTED K1 RED)
(TEMPERATURE K1 COLD)
(HAS-HOLE K1 TWO FRONT)

(SHAPE L1 OBLONG)
(SURFACE-CONDITION L1 ROUGH)
(PAINTED L1 BLUE)
(TEMPERATURE L1 COLD)
(HAS-HOLE L1 TWO BACK)

(SHAPE M1 OBLONG)
(SURFACE-CONDITION M1 POLISHED)
(PAINTED M1 RED)
(TEMPERATURE M1 COLD)
(HAS-HOLE M1 TWO FRONT)

(SHAPE N1 OBLONG)
(SURFACE-CONDITION N1 ROUGH)
(PAINTED N1 BLACK)
(TEMPERATURE N1 COLD)
(HAS-HOLE N1 TWO BACK)

(SHAPE O1 CYLINDRICAL)
(SURFACE-CONDITION O1 ROUGH)
(PAINTED O1 BLACK)
(TEMPERATURE O1 COLD)
(HAS-HOLE O1 TWO FRONT)

(SHAPE P1 CYLINDRICAL)
(SURFACE-CONDITION P1 POLISHED)
(PAINTED P1 BLACK)
(TEMPERATURE P1 COLD)
(HAS-HOLE P1 TWO FRONT)

(SHAPE Q1 OBLONG)
(SURFACE-CONDITION Q1 ROUGH)
(PAINTED Q1 YELLOW)
(TEMPERATURE Q1 COLD)
(HAS-HOLE Q1 TWO BACK)

(SHAPE R1 OBLONG)
(SURFACE-CONDITION R1 ROUGH)
(PAINTED R1 BLACK)
(TEMPERATURE R1 COLD)
(HAS-HOLE R1 ONE BACK)

(SHAPE S1 CYLINDRICAL)
(SURFACE-CONDITION S1 ROUGH)
(PAINTED S1 YELLOW)
(TEMPERATURE S1 COLD)
(HAS-HOLE S1 TWO FRONT)

(SHAPE U1 OBLONG)
(SURFACE-CONDITION U1 POLISHED)
(PAINTED U1 YELLOW)
(TEMPERATURE U1 COLD)
(HAS-HOLE U1 THREE BACK)

(SHAPE V1 OBLONG)
(SURFACE-CONDITION V1 SMOOTH)
(PAINTED V1 YELLOW)
(TEMPERATURE V1 COLD)
(HAS-HOLE V1 TWO BACK)

(SHAPE W1 CIRCULAR)
(SURFACE-CONDITION W1 ROUGH)
(PAINTED W1 BLACK)
(TEMPERATURE W1 COLD)
(HAS-HOLE W1 THREE BACK)

(SHAPE Z1 OBLONG)
(SURFACE-CONDITION Z1 SMOOTH)
(PAINTED Z1 BLACK)
(TEMPERATURE Z1 COLD)
(HAS-HOLE Z1 ONE BACK)

(SHAPE A2 OBLONG)
(SURFACE-CONDITION A2 ROUGH)
(PAINTED A2 BLACK)
(TEMPERATURE A2 COLD)
(HAS-HOLE A2 TWO FRONT)

(SHAPE B2 OBLONG)
(SURFACE-CONDITION B2 SMOOTH)
(PAINTED B2 BLUE)
(TEMPERATURE B2 COLD)
(HAS-HOLE B2 THREE FRONT)

(SHAPE C2 OBLONG)
(SURFACE-CONDITION C2 SMOOTH)
(PAINTED C2 BLUE)
(TEMPERATURE C2 COLD)
(HAS-HOLE C2 TWO FRONT)

(SHAPE D2 CIRCULAR)
(SURFACE-CONDITION D2 ROUGH)
(PAINTED D2 BLACK)
(TEMPERATURE D2 COLD)
(HAS-HOLE D2 THREE BACK)

(SHAPE E2 CYLINDRICAL)
(SURFACE-CONDITION E2 ROUGH)
(PAINTED E2 YELLOW)
(TEMPERATURE E2 COLD)
(HAS-HOLE E2 TWO FRONT)

(SHAPE F2 CIRCULAR)
(SURFACE-CONDITION F2 ROUGH)
(PAINTED F2 BLUE)
(TEMPERATURE F2 COLD)
(HAS-HOLE F2 ONE FRONT)

(SHAPE G2 OBLONG)
(SURFACE-CONDITION G2 ROUGH)
(PAINTED G2 BLACK)
(TEMPERATURE G2 COLD)
(HAS-HOLE G2 TWO FRONT)

(SHAPE H2 CIRCULAR)
(SURFACE-CONDITION H2 SMOOTH)
(PAINTED H2 BLUE)
(TEMPERATURE H2 COLD)
(HAS-HOLE H2 TWO BACK)

(SHAPE I2 OBLONG)
(SURFACE-CONDITION I2 POLISHED)
(PAINTED I2 YELLOW)
(TEMPERATURE I2 COLD)
(HAS-HOLE I2 ONE BACK)

(SHAPE J2 OBLONG)
(SURFACE-CONDITION J2 ROUGH)
(PAINTED J2 BLACK)
(TEMPERATURE J2 COLD)
(HAS-HOLE J2 TWO FRONT)

(SHAPE K2 CYLINDRICAL)
(SURFACE-CONDITION K2 ROUGH)
(PAINTED K2 RED)
(TEMPERATURE K2 COLD)
(HAS-HOLE K2 THREE BACK)

(SHAPE L2 CYLINDRICAL)
(SURFACE-CONDITION L2 ROUGH)
(PAINTED L2 BLACK)
(TEMPERATURE L2 COLD)
(HAS-HOLE L2 ONE BACK)

(SHAPE M2 OBLONG)
(SURFACE-CONDITION M2 SMOOTH)
(PAINTED M2 BLUE)
(TEMPERATURE M2 COLD)
(HAS-HOLE M2 THREE FRONT)

(SHAPE N2 CIRCULAR)
(SURFACE-CONDITION N2 ROUGH)
(PAINTED N2 BLUE)
(TEMPERATURE N2 COLD)
(HAS-HOLE N2 ONE BACK)

    (CAN-ORIENT DRILL-PRESS BACK)
    (CAN-ORIENT PUNCH BACK)
    (CAN-ORIENT DRILL-PRESS FRONT)
    (CAN-ORIENT PUNCH FRONT)

    (HAS-PAINT IMMERSION-PAINTER YELLOW)
    (HAS-PAINT SPRAY-PAINTER YELLOW)
    (HAS-PAINT IMMERSION-PAINTER BLUE)
    (HAS-PAINT SPRAY-PAINTER BLUE)
    (HAS-PAINT IMMERSION-PAINTER BLACK)
    (HAS-PAINT SPRAY-PAINTER BLACK)
    (HAS-PAINT IMMERSION-PAINTER RED)
    (HAS-PAINT SPRAY-PAINTER RED)

    (HAS-BIT DRILL-PRESS THREE)
    (HAS-BIT PUNCH THREE)
    (HAS-BIT DRILL-PRESS TWO)
    (HAS-BIT PUNCH TWO)
    (HAS-BIT DRILL-PRESS ONE)
    (HAS-BIT PUNCH ONE)

    (PART N2)
    (PART M2)
    (PART L2)
    (PART K2)
    (PART J2)
    (PART I2)
    (PART H2)
    (PART G2)
    (PART F2)
    (PART E2)
    (PART D2)
    (PART C2)
    (PART B2)
    (PART A2)
    (PART Z1)
    (PART W1)
    (PART V1)
    (PART U1)
    (PART S1)
    (PART R1)
    (PART P1)
    (PART Q1)
    (PART O1)
    (PART N1)
    (PART M1)
    (PART L1)
    (PART K1)
    (PART J1)
    (PART I1)
    (PART H1)
    (PART G1)
    (PART F1)
    (PART E1)
    (PART D1)
    (PART C1)
    (PART B1)
    (PART A1)
    (PART Z0)
    (PART W0)
    (PART V0)
    (PART U0)
    (PART S0)
    (PART R0)
    (PART P0)
    (PART Q0)
    (PART O0)
    (PART N0)
    (PART M0)
    (PART L0)
    (PART K0)
    (PART J0)
    (PART I0)
    (PART H0)
    (PART G0)
    (PART F0)
    (PART E0)
    (PART D0)
    (PART C0)
    (PART B0)
    (PART A0)
)
(:goal (and

(SHAPE A0 CYLINDRICAL)
(SURFACE-CONDITION A0 POLISHED)
(PAINTED A0 BLUE)

(SURFACE-CONDITION B0 SMOOTH)
(PAINTED B0 YELLOW)

(SHAPE C0 CYLINDRICAL)
(SURFACE-CONDITION C0 SMOOTH)
(PAINTED C0 RED)

(SURFACE-CONDITION D0 POLISHED)
(PAINTED D0 RED)

(SHAPE E0 CYLINDRICAL)
(SURFACE-CONDITION E0 SMOOTH)
(PAINTED E0 BLACK)

(SHAPE F0 CYLINDRICAL)
(SURFACE-CONDITION F0 POLISHED)
(PAINTED F0 BLACK)

(SHAPE G0 CYLINDRICAL)
(SURFACE-CONDITION G0 SMOOTH)
(PAINTED G0 BLUE)

(SHAPE H0 CYLINDRICAL)
(SURFACE-CONDITION H0 POLISHED)
(PAINTED H0 BLACK)

(SHAPE I0 CYLINDRICAL)
(SURFACE-CONDITION I0 POLISHED)
(PAINTED I0 BLACK)

(SURFACE-CONDITION J0 SMOOTH)
(PAINTED J0 BLUE)

(SHAPE K0 CYLINDRICAL)
(SURFACE-CONDITION K0 POLISHED)
(PAINTED K0 RED)

(SHAPE L0 CYLINDRICAL)
(SURFACE-CONDITION L0 SMOOTH)
(PAINTED L0 BLACK)

(SURFACE-CONDITION M0 POLISHED)
(PAINTED M0 BLACK)

(SHAPE N0 CYLINDRICAL)
(SURFACE-CONDITION N0 POLISHED)
(PAINTED N0 BLACK)

(SHAPE O0 CYLINDRICAL)
(SURFACE-CONDITION O0 SMOOTH)
(PAINTED O0 BLUE)

(SHAPE P0 CYLINDRICAL)
(SURFACE-CONDITION P0 ROUGH)
(PAINTED P0 RED)

(SHAPE Q0 CYLINDRICAL)
(SURFACE-CONDITION Q0 POLISHED)
(PAINTED Q0 BLUE)

(SHAPE R0 CYLINDRICAL)
(SURFACE-CONDITION R0 SMOOTH)
(PAINTED R0 YELLOW)

(SHAPE S0 CYLINDRICAL)
(SURFACE-CONDITION S0 POLISHED)
(PAINTED S0 BLACK)

(SHAPE U0 CYLINDRICAL)
(SURFACE-CONDITION U0 SMOOTH)
(PAINTED U0 YELLOW)

(SURFACE-CONDITION V0 POLISHED)
(PAINTED V0 YELLOW)

(SHAPE W0 CYLINDRICAL)
(SURFACE-CONDITION W0 SMOOTH)
(PAINTED W0 YELLOW)

(SHAPE Z0 CYLINDRICAL)
(SURFACE-CONDITION Z0 POLISHED)
(PAINTED Z0 BLUE)

(SHAPE A1 CYLINDRICAL)
(SURFACE-CONDITION A1 ROUGH)
(PAINTED A1 RED)

(SHAPE B1 CYLINDRICAL)
(SURFACE-CONDITION B1 POLISHED)
(PAINTED B1 BLACK)

(SHAPE C1 CYLINDRICAL)
(SURFACE-CONDITION C1 POLISHED)
(PAINTED C1 YELLOW)

(SHAPE D1 CYLINDRICAL)
(SURFACE-CONDITION D1 POLISHED)
(PAINTED D1 BLACK)

(SHAPE E1 CYLINDRICAL)
(SURFACE-CONDITION E1 SMOOTH)
(PAINTED E1 YELLOW)

(SHAPE F1 CYLINDRICAL)
(SURFACE-CONDITION F1 SMOOTH)
(PAINTED F1 RED)

(SHAPE G1 CYLINDRICAL)
(SURFACE-CONDITION G1 POLISHED)
(PAINTED G1 BLUE)

(SHAPE H1 CYLINDRICAL)
(SURFACE-CONDITION H1 ROUGH)
(PAINTED H1 BLACK)

(SHAPE I1 CYLINDRICAL)
(SURFACE-CONDITION I1 SMOOTH)
(PAINTED I1 BLUE)

(SHAPE J1 CYLINDRICAL)
(SURFACE-CONDITION J1 ROUGH)
(PAINTED J1 BLUE)

(SHAPE K1 CYLINDRICAL)
(SURFACE-CONDITION K1 POLISHED)
(PAINTED K1 YELLOW)

(SHAPE L1 CYLINDRICAL)
(SURFACE-CONDITION L1 POLISHED)
(PAINTED L1 BLACK)

(SHAPE M1 CYLINDRICAL)
(SURFACE-CONDITION M1 SMOOTH)
(PAINTED M1 YELLOW)

(SHAPE N1 CYLINDRICAL)
(SURFACE-CONDITION N1 POLISHED)
(PAINTED N1 RED)

(SURFACE-CONDITION O1 POLISHED)
(PAINTED O1 RED)

(SURFACE-CONDITION P1 SMOOTH)
(PAINTED P1 RED)

(SHAPE Q1 CYLINDRICAL)
(SURFACE-CONDITION Q1 POLISHED)
(PAINTED Q1 BLUE)

(SHAPE R1 CYLINDRICAL)
(SURFACE-CONDITION R1 POLISHED)
(PAINTED R1 RED)

(SURFACE-CONDITION S1 POLISHED)
(PAINTED S1 BLUE)

(SHAPE U1 CYLINDRICAL)
(SURFACE-CONDITION U1 SMOOTH)
(PAINTED U1 BLUE)

(SHAPE V1 CYLINDRICAL)
(SURFACE-CONDITION V1 ROUGH)
(PAINTED V1 BLUE)

(SHAPE W1 CYLINDRICAL)
(SURFACE-CONDITION W1 POLISHED)
(PAINTED W1 RED)

(SHAPE Z1 CYLINDRICAL)
(SURFACE-CONDITION Z1 ROUGH)
(PAINTED Z1 RED)

(SHAPE A2 CYLINDRICAL)
(SURFACE-CONDITION A2 POLISHED)
(PAINTED A2 RED)

(SHAPE B2 CYLINDRICAL)
(SURFACE-CONDITION B2 ROUGH)
(PAINTED B2 BLACK)

(SHAPE C2 CYLINDRICAL)
(SURFACE-CONDITION C2 ROUGH)
(PAINTED C2 BLACK)

(SHAPE D2 CYLINDRICAL)
(SURFACE-CONDITION D2 POLISHED)
(PAINTED D2 RED)

(SURFACE-CONDITION E2 POLISHED)
(PAINTED E2 BLUE)

(SHAPE F2 CYLINDRICAL)
(SURFACE-CONDITION F2 POLISHED)
(PAINTED F2 BLACK)

(SHAPE G2 CYLINDRICAL)
(SURFACE-CONDITION G2 POLISHED)
(PAINTED G2 RED)

(SHAPE H2 CYLINDRICAL)
(SURFACE-CONDITION H2 ROUGH)
(PAINTED H2 BLACK)

(SHAPE I2 CYLINDRICAL)
(SURFACE-CONDITION I2 SMOOTH)
(PAINTED I2 BLUE)

(SHAPE J2 CYLINDRICAL)
(SURFACE-CONDITION J2 POLISHED)
(PAINTED J2 RED)

(SURFACE-CONDITION K2 POLISHED)
(PAINTED K2 YELLOW)

(SURFACE-CONDITION L2 POLISHED)
(PAINTED L2 RED)

(SHAPE M2 CYLINDRICAL)
(SURFACE-CONDITION M2 ROUGH)
(PAINTED M2 BLACK)

(SHAPE N2 CYLINDRICAL)
(SURFACE-CONDITION N2 POLISHED)
(PAINTED N2 BLACK)

)))
